### ISSUE TITLE
Resizeable window cutting off  at orignal size

### ISSUE THREAD

**Issue by Dcat682** [Colossus-Gaming/retroachievements-layout-manager#10]
I'm running the version you posted a few  weeks back allowing us to resize windows for monitors at >100% scaling.  I booted it up yesterday and all of my settings were reset to default and the window for the capture gets cut off at the default resolution.  When stretched the background turns white and cuts off the image.

![image](https://user-images.githubusercontent.com/42703999/230211313-4f962328-6fee-4af3-9b5c-e3b9bec2d8b9.png)

**Comment by lrhodes404** [comment]
Resizing windows was never an intended feature and the new version works with DPI scaling on the desktop. Please open another ticket if you experience anymore issues.
