### ISSUE TITLE
1.24.1 has a number of bugs

### ISSUE THREAD

**Issue by AquaJew** [Colossus-Gaming/retroachievements-layout-manager#11]
The window sizes seem enlarged; I can no longer fit my previous open windows on one monitor. It is hard to test why this is because a few of the windows no longer populate with any info at all, namely User Info, Game Info, and Progress. Just empty windows that open.

My username and API key are still valid, as the Achievement List, Media, and Recent Unlocks still work.

**Comment by lrhodes404** [comment]
Update released and seems to have fixed the issue. Please re-open if you're still experiencing issues.
