### ISSUE TITLE
Tracker 1.25.2 stuck on one game

### ISSUE THREAD

**Issue by ZetaZeroSnow** [Colossus-Gaming/retroachievements-layout-manager#13]
So currently on ver 1.25.2, my main account shows as Gran Turismo 4 and will not update at all, even on a new achievement unlock on a completely different game based on the changelog with how it updates based on a new cheevo pop. This all happened as the API went down roughly a week ago. I have reset my api key a few times in hopes that it will fix it but no luck. However, if i use anything lower than 1.25.2/1.25.1, the games will update but not track correctly such as auto-focus going to the next cheevo or tracking stats like progress completion or cheevo number. It also does not update when I unlock a cheevo and it stays loaded into  memory in both the focus tab and the cheevo list tab. I played around with an alt account, loading GT4 and playing another game back and forth and those updated just fine with all things such as auto-focus, stats, etc working. Using Launchbox Clear Logo's, Related Media is also a mess given it displays Ape Escape 2 for anything PS2 loaded and blank for anything else. Edit 1: Still the same with 1.25.3

**Comment by lrhodes404** [comment]
Other users have reported similar issues but have had to do things like make a new account to put in the tracker. It can only use what is returned from the API and I cannot code around that. For the Related Media window to work, there has to be a valid file present and the game must be launched from LaunchBox. Closing this issue as this not something a code release will not fix.
