### ISSUE TITLE
"Related Media" doesn't auto-update between games?!

### ISSUE THREAD

**Issue by AbsoLootAaron** [Colossus-Gaming/retroachievements-layout-manager#14]
It seems like Focus, Progress, and Achievement List all auto-update when I switch between games, except for Related Media. So I'm forced to manually update Related Media every time for a new game, by clicking Box Art in the application.
I've also noticed that if I don't manually update, the 3rd game and onwards will have the previous games Box Art instead, kind of like it's always lagging behind by one game when I only let it auto-update.
So frustrating! lol
Hopefully this will be an easy fix for you. :)

P.S. When it just auto-updates, the Related Media will "act" like it's about to update the Box Art for the new game, bc the Box Art on-screen will slide to the right, but when it comes back it's just the same/previous Box Art.

**Comment by lrhodes404** [comment]
Moved the Related Media update to the proper code block. Should update correctly now.

**Comment by AbsoLootAaron** [comment]
Thanks buddy! I just started using this thing, so if I run into another weird problem, I'll leave another issue on here for ya. :)
