### ISSUE TITLE
Stream-labels for last-five display wrong data

### ISSUE THREAD

**Issue by gorocz** [Colossus-Gaming/retroachievements-layout-manager#15]
Looks like the txt files for stream-labels of the last-five achievements contain info about the first 5 achievements in the set by id, instead of the last five achievements achieved. 

The output window in the actual application is correct.

Using version v1.25.6

**Comment by lrhodes404** [comment]
Added the necessary lines to sort and reverse the achievement list before traversing it when writing text files. Thanks for letting me know.
