### ISSUE TITLE
wont start anymore

### ISSUE THREAD

**Issue by tayhbth** [Colossus-Gaming/retroachievements-layout-manager#17]
i can open the app just fine but when i click START i get an error saying the WEB API IS NOT RESPONDING SUCCESSSFULLY. THIS WILL PREVENT THE TRACKER FROM GETTING INFORMATION FROM THE SITE. Ive had this issue in the past but it fixed itself after a few hours. now its happening again and its been a week with no fix. any help please? i changed my API Mutiple times but that didn't work and I've uninstalled and reinstalled the program with also no fix. i also attached a screenshot. idk if it will show for you or not.

![bandicam 2023-06-23 12-05-24-862](https://github.com/Colossus-Gaming/retroachievements-layout-manager/assets/137556051/75fd5c29-a237-4652-82fd-74003bfe9469)

**Comment by Tarneris** [comment]
I am experiencing the same issue.

**Comment by 90sCraig** [comment]
Same issue here. Guessing something has changed with the RA api.

**Comment by 90sCraig** [comment]
As a follow-up, it appears that RA has taken the API offline for the time being. This is from the discord:

> there were problems which made the site very slow, afaik there is no time frame atm when its gonna be back up

**Comment by lrhodes404** [comment]
I do not own the Retro Achievements API and they are working on a fix. Closing this issue.
