### ISSUE TITLE
Last Five Achievements Problem

### ISSUE THREAD

**Issue by SilverTriforce** [Colossus-Gaming/retroachievements-layout-manager#2]
Hi,

I have a problem with the Last Five Achievements Panel. Every time i get a new achievement, every achievements in this panel disappear. I have to close the panel and reopen it to reload the last five but it's a little bit annoying. Are you able to help on this issue ?

Thanks and have a good day.

**Comment by lrhodes404** [comment]
Hi! Yes, I will be looking into it. I'm currently refactoring the app to make it easier to maintain and then I'll make sure the Last Five is consistent.

**Comment by lrhodes404** [comment]
I put out an update that should resolve this and also help tidy up a few things. Going to close this issue for now since an attempted fix is out and will reopen if necessary.
