### ISSUE TITLE
Window size problem with latest update

### ISSUE THREAD

**Issue by Ekiinoxx** [Colossus-Gaming/retroachievements-layout-manager#21]
Hi.

With the removal of the user info and the resizing of the main window, the sub-windows no longer have the right size ratio and everything is cut off (for the game info and the focus). I don't know if this is normal.

![2023-11-26_134952](https://github.com/Colossus-Gaming/retroachievements-layout-manager/assets/151623927/3926455a-8927-42d6-b532-8f216193c79c)
![2023-11-26_135003](https://github.com/Colossus-Gaming/retroachievements-layout-manager/assets/151623927/91b7f948-74c5-4a4b-a5aa-3cf034725a7f)

**Comment by lrhodes404** [comment]
This is caused by user settings on the desktop and not something I can control.
