### ISSUE TITLE
Some QoL Option Requests?

### ISSUE THREAD

**Issue by Chromagram** [Colossus-Gaming/retroachievements-layout-manager#27]
Hello,

First off, thank you for this tool! As someone who almost exclusively streams RetroAchievements, this is going to be an excellent help to keep track of everything and make it visually interesting for viewers. I do like basically most of what the program offers, but I was hoping to request just a couple small potential options to really nail down the final look of what I was hoping to use.

1. Could we get a way to disable the little points text on the achievement icons? For me, it covers a good chunk of the fun custom icons developers make for the achievements, and the number of points for the achievement and displaying it is nowhere near as important for me personally. If I really did want to see/show it, I can hover over the icon in the Achievement List popup to see it, and I also have a Chrome window I can show in OBS to just go to the RA site and see the points there too.

2. Regarding the other text elements like Title and Description, it's very nice we can have custom fonts. However, it would be really great if we could customize the font size for these. I personally would like to have the description be a smaller size font so the text both Title and Description doesn't really kind of look like one text blob, especially if you use the same font and colour for both. Additional ways to help that may be to allow customizing if you want the separator line or not, and to maybe allow editing how thick that separator line is.

3. Regarding background colour options, could we get an alpha channel option to the colour picker? That, or the ability to just have a fully transparent option? Right now, it seems like you just pick a background colour, and then you add a Chroma Key filter in OBS to key out that colour. It works for the most part, but when that colour you key out also exists in the achievement icon, it dulls/kills that colour there too. Just allowing transparency as a colour or an alpha slider so we can set it ourselves would fully fix this.

4. It is possible so that just by clicking an achievement icon in the Achievement List window, it sets that achievement to the active one in Focus automatically? Saves having to dig through long achievement lists that are hundreds of achievements long to set a particular one as active. Much easier to just find a matching icon, hovering over it in the Achievements List to confirm it's the one, then clicking it to set it.

Again, mostly happy with it and can't complain at all about the overall usage. These things would just really make it perfect for me personally, so I wanted to submit them.

Thanks again for this!

**Comment by Thedragon005** [comment]
If I may add to this, my friend brought up a good point for the Achievements List :
Is there a way you could implement parameters to set the number of columns (up to a maximum) so that it could be resizable ?
That way it could be more of a resizable windows without breaking it by manually resizing it.

If possible, thanks !

**Comment by ProfessorLaw** [comment]
Hi there, working on these. 

I don't know if this is still maintained but I might do a release compiling these changes anyway as I had some fixes I wanted to do for myself, too. (Never worked on .NET projects before so it might take some time before it happens ^^")

@Chromagram 
* Point 1 and 4 are done on my end (Double clicking on an achievement in the achievement list to set the focus is actually neat !). 
* Point 3 can't be done because of a technical limitation. I am able to programatically make the window looks transparent however the underlying system would work with a Chroma key too so this wouldn't change anything regarding the behaviour you're experiencing now. So I guess I won't be changing anything here.
* I might check at Point 2 later.

@Thedragon005 
* I'll try to implement something where you can set a number of line and columns visible by default (more lines than defined will make the list scroll as it does today).

**Comment by NicoPlaysThings** [comment]
@ProfessorLaw The problem with the transparency, is that it would need to be a webpage, not in webview, that could be loaded as a browser source in obs as it is the only way to do transparency

**Comment by ProfessorLaw** [comment]
> Hey again, sorry I forgot to bring this up, but there was one more thing I needed to point out and request:
> 
> Sometimes I use the Achievement List window to check what achievement descriptions are. The hover tooltip box is nice, but on the right edge of the window, the tooltip comes up and gets cut off by the edge of the window and you can't read the text. I attached a screenshot to show an example.
> 
> I think allowing the tooltip to escape the bounds of the window or maybe doing a single click to preview a separate floating tooltip and making the "click to make achievement active" action a double click could do?
> 
> ![Screenshot 2024-08-12 020936](https://private-user-images.githubusercontent.com/44986450/356991206-286a857c-ceca-43f8-967c-bc395d5b218c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTQyMTgsIm5iZiI6MTcyMzQ1MzkxOCwicGF0aCI6Ii80NDk4NjQ1MC8zNTY5OTEyMDYtMjg2YTg1N2MtY2VjYS00M2Y4LTk2N2MtYmMzOTVkNWIyMThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA5MTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNDAyZDE2YjkwMWMxMTI5OTcyOGY0ZTg5NjZiZTEwZDBkMTQ3ODA0MzQ2ZDYzOWUzOGI3MjRmMjJmOTQyYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KE_I7ArvpITo5rpX0gT4rHXQvQeRhNf_dh_YHnW3YD0)

Hi,

I already reported this in #29  and fixed it in #30 as I had the same issue :)

**Comment by ProfessorLaw** [comment]
Hello,

I've been testing some of these changes locally lately to try them but yeah I should release them.

I still need to figure out how to do a proper release and I'll try to make one on my fork.

I'll keep you informed as soon as it's done !

**Comment by ProfessorLaw** [comment]
> I can help facilitate releases on this page or show you how I've been doing it. I appreciate everyone's help on keeping this alive.

Hey, yes for sure !
As of now I've been able to generate an MSI from VS2022 using the Installer Project extension (that's basically what I understood Googling it, I never built that kind of projects before)

Now I'm trying to automate the releases through GitHub Actions (prereleases when merging on master, proper releases using tags), but I may have missed some stuff I don't know but I should care about so if you've got any info, that would be nice to have !

Thank you ! :)

**Comment by lrhodes404** [comment]
If you're able to get the app project and installer project there are a few versioning numbers that need to be incremented:
```- Assembly Information -> Assembly Version (usually mirrors the release number)
- Assembly Information -> File Version (usually mirrors the release number)
- Installer Project -> Version (within VS this triggers an update to the ProductCode; not sure about GHA)
```
For cutting a release that can be auto-updated to, you'll need to edit the XML file found [here](https://github.com/Colossus-Gaming/retroachievements-layout-manager/releases/tag/release-management). Update the <version> and <url> fields, then edit the release to add the new XML. I have also enabled Discussions if anyone wants to suggest features there.
