### ISSUE TITLE
Updating not working

### ISSUE THREAD

**Issue by Drachnix** [Colossus-Gaming/retroachievements-layout-manager#28]
I wanna stream my future gamplay with collecting archevments. I wanna use the rero archevment tracker.
I installed the programm and run.

I can start the tracking and the update countdown count to 0. but the tracker dont track the archevments.
in RA website the archivment is tracked, but the tracker not work. i wiat 5 minutes and more, but now tracked archivment.

The tracker is start as admin.

How can i fix that?

**Comment by NicoPlaysThings** [comment]
I looked at your profile and there are no achievements on it, are you sure you are earning achievements?

**Comment by Drachnix** [comment]
Yes, i delated earned archevments, because i wanna earn them on stream. i used the tracker, earned some archevments and the tracker doesent track them. after that i delete the archenments, for livestream to eran them new for the viewers :)

**Comment by NicoPlaysThings** [comment]
Are you earning the achievements in hardcore mode? This app only works when earning achievements in hardcore mode.

**Comment by ProfessorLaw** [comment]
Hi,
Hardcore mode for achievements means you can't use cheats, rewind, savestates etc. They give (more) points and are shown differently (they have a colored border)
Have fun !
