### ISSUE TITLE
Achievement list issue.

### ISSUE THREAD

**Issue by devoidv3** [Colossus-Gaming/retroachievements-layout-manager#3]
Hello, when I have the achievement list open it seems to cut off part of the last one for the row and if I try to resize the window its just filled with white space (closing and re opening the window results in a blank window)
<img width="559" alt="Screenshot_80" src="https://user-images.githubusercontent.com/2057850/189039403-d44ffc33-e808-4685-a0e3-b921febb6317.png">

**Comment by devoidv3** [comment]
The issues seems to correct itself 80% of the time on auto open.

**Comment by lrhodes404** [comment]
I tried to disable resize since the window is supposed to be a static size. The list should populate no matter when the window is opened from now on.
