### ISSUE TITLE
Allow App to update faster?

### ISSUE THREAD

**Issue by AlanEight** [Colossus-Gaming/retroachievements-layout-manager#32]
Is there any way to allow this app to update faster, like every second? I am using this while recording, and I don't like that I have to sometimes wait the full 30 seconds for my overlay to update with my recent achievement earned.

**Comment by NicoPlaysThings** [comment]
That wouldn't practical as you would end up having your API key get limited after a couple seconds.

**Comment by AlanEight** [comment]
I wasn’t aware of that. Your API key gets limited if it is used too often?

**Comment by NicoPlaysThings** [comment]
Yes it does, the limit is undocumented for spam reasons but I can guarantee you that spamming the API every second will reach that limit and make it end up not working.
