### ISSUE TITLE
Does not detect previously completed achievements

### ISSUE THREAD

**Issue by Madcore** [Colossus-Gaming/retroachievements-layout-manager#5]
When I connect my account and start a game, it does not detect the achievements that I have already achieved. I reset the Super Mario World achievements to try to get them again and see if that was the problem, but when I get two achievements again, the program does not detect them and does not list them when I log in again.

I attach the debug.log in case it can help.

[debug.log](https://github.com/Colossus-Gaming/retroachievements-layout-manager/files/9794784/debug.log)

**Comment by lrhodes404** [comment]
Are you achieving these on Hardcore mode? The application only recognizes achievements with a Hardcore unlock datetime.

**Comment by Madcore** [comment]
I'm not playing in Hardcore mode.

**Comment by lrhodes404** [comment]
Since the app is only intended to track hardcore achievements, I'm closing this issue.
