### ISSUE TITLE
Alert Stuck

### ISSUE THREAD

**Issue by jvlk123** [Colossus-Gaming/retroachievements-layout-manager#6]
It seems Achievement Alert is stuck it goes down but not up again. That's with the test achievement "Are you Ready?"

**Comment by lrhodes404** [comment]
Can you give more details as to what happened? I don't understand the issue and would need details to assess what the issue really is.

**Comment by jvlk123** [comment]
Cheevo Alerts TAB, When I Open the RA Tracker Alert window, The "TEST" achievement pops up and goes down to middle of the window. But than it is stuck and does not go away again. It should go back up again and disappear right?

**Comment by jvlk123** [comment]
Nevermind, I never clicked the window. Feeling stupid now.
