### ISSUE TITLE
Client won't  leave "Booting. Please stand by" state

### ISSUE THREAD

**Issue by DaRabidDuckie** [Colossus-Gaming/retroachievements-layout-manager#7]
The client won't leave "Booting. Please stand by" state. Pressing stop and then start acts like it's connecting but won't update user info. Tried reinstalling and running as admin with no result. Issue started with v1.22.1 and has persisted with latest updates.

**Comment by lrhodes404** [comment]
Another user reported this issue and the latest update was able to resolve this issue. Have you tried stopping the app and re-inputting your credentials with the latest version? If so, I can try to help troubleshoot/investigate over Discord. If it is still failing with the latest version, there should also be an "error.log" file that is output in the app's root directory and that would be helpful.

**Comment by DaRabidDuckie** [comment]
I reinput my credentials and that didn't work, however I reset my web api key (for the third time) and it works now. What's that old saying, that it never works until someone else looks at it? Either way, consider this one closed. Thanks for the quick reply.
