### ISSUE TITLE
Recent Unlocks window does not populate 

### ISSUE THREAD

**Issue by AquaJew** [Colossus-Gaming/retroachievements-layout-manager#9]
All other windows seem to open fine, and pulls data from my RA account. The Recent Unlocks window will open at a size of 0x0, and can be maximized to show just a magenta square (I'm guessing the size of the normal window), but no achievements will be listed, even when waiting.

**Comment by AquaJew** [comment]
Looks like a few restarts and opening/closing RetroArch got this to work. It also seems like this is game specific - based on the last game I played, and not the last 5 global achievements I have earned.

**Comment by lrhodes404** [comment]
Working on a fix for this. New update will include a fix for this, a prompt to not get auto-update alerts for a particular version, button to check for updates, and maintaining the DPI sensitivity of the machine it's running on. Thank you for being patient.

**Comment by lrhodes404** [comment]
Update is available at https://github.com/Colossus-Gaming/retroachievements-layout-manager/releases/tag/v1.24.1 if you are using the hotfix version with resizable windows that I put out a few weeks ago. The current version should auto-update to this version but prompt for future updates moving forward. Recent Unlocks should now start updating with achievement pops as expected.
